# Generated by Django 6.0.2 on 2026-05-08 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('feedback_type', models.CharField(choices=[('suggestion', 'پیشنهاد'), ('bug', 'گزارش باگ'), ('question', 'سوال'), ('other', 'سایر')], default='suggestion', max_length=20, verbose_name='نوع بازخورد')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'بازخورد',
                'verbose_name_plural': 'بازخوردها',
                'ordering': ['-created_at'],
            },
        ),
    ]
