# Generated by Django 6.0.2 on 2026-05-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('suggestion', 'پیشنهاد'), ('search_problem,', 'مشکل جستجوی آیه'), ('bug', 'گزارش باگ'), ('question', 'سوال'), ('other', 'سایر')], default='suggestion', max_length=20, verbose_name='نوع بازخورد'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
    ]
