# Generated by Django 6.0.2 on 2026-05-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedback_email_remove_feedback_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('suggestion', 'پیشنهاد'), ('search_problem', 'مشکل جستجوی آیه'), ('bug', 'گزارش باگ'), ('question', 'سوال'), ('other', 'سایر')], default='suggestion', max_length=20, verbose_name='نوع بازخورد'),
        ),
    ]
