# Generated by Django 6.0.2 on 2026-05-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('quran', '0015_alter_tafsirsource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allowed_surah_list',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='quran.surah', verbose_name='سوره\u200cهای مجاز'),
        ),
    ]
