# Generated by Django 6.0.2 on 2026-04-22 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سوره')),
                ('persian_name', models.CharField(max_length=100, verbose_name='نام فارسی سوره')),
                ('latin_name', models.CharField(max_length=100, verbose_name='نام لاتین سوره')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='شماره سوره')),
                ('total_verses', models.PositiveSmallIntegerField(verbose_name='تعداد آیات')),
            ],
            options={
                'verbose_name': 'سوره',
                'verbose_name_plural': 'سوره\u200cها',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='شماره آیه در سوره')),
                ('text', models.TextField(verbose_name='متن کامل آیه (عربی)')),
                ('text_prefix', models.CharField(blank=True, max_length=50, verbose_name='۲۰ کاراکتر اول آیه (برای نمایش سریع)')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='quran.surah', verbose_name='سوره')),
            ],
            options={
                'verbose_name': 'آیه',
                'verbose_name_plural': 'آیات',
                'ordering': ['surah__number', 'number'],
                'unique_together': {('surah', 'number')},
            },
        ),
    ]
