# Generated by Django 6.0.2 on 2026-04-22 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tafsir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, verbose_name='نام مفسر / منبع تفسیر')),
                ('text', models.TextField(verbose_name='متن تفسیر')),
                ('order_priority', models.PositiveSmallIntegerField(default=1, verbose_name='اولویت ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tafsirs', to='quran.ayah', verbose_name='آیه مرتبط')),
            ],
            options={
                'verbose_name': 'تفسیر',
                'verbose_name_plural': 'تفاسیر',
                'ordering': ['order_priority', 'source'],
                'indexes': [models.Index(fields=['ayah', 'order_priority'], name='quran_tafsi_ayah_id_1665c3_idx')],
            },
        ),
    ]
