# Generated by Django 6.0.2 on 2026-04-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_tafsir'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayah',
            name='text_fa',
            field=models.TextField(blank=True, verbose_name='متن کامل آیه (عربی)'),
        ),
        migrations.AlterField(
            model_name='surah',
            name='latin_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام لاتین سوره'),
        ),
        migrations.AlterField(
            model_name='surah',
            name='persian_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام فارسی سوره'),
        ),
    ]
