# Generated by Django 6.0.2 on 2026-04-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0003_ayah_text_fa_alter_surah_latin_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surah',
            name='persian_second_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام دوم'),
        ),
        migrations.AddField(
            model_name='surah',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام دوم'),
        ),
    ]
