# Generated by Django 6.0.2 on 2026-04-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0004_surah_persian_second_name_surah_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surah',
            name='persian_second_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام دوم فارسی'),
        ),
    ]
