# Generated by Django 6.0.2 on 2026-04-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0005_alter_surah_persian_second_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TafsirSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tafsir',
            options={'ordering': ['order_priority'], 'verbose_name': 'تفسیر', 'verbose_name_plural': 'تفاسیر'},
        ),
        migrations.RemoveField(
            model_name='tafsir',
            name='source',
        ),
    ]
