# Generated by Django 6.0.2 on 2026-04-23 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0006_tafsirsource_alter_tafsir_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tafsir',
            name='tafsir_source',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tafsirs', to='quran.tafsirsource', verbose_name='منبع تفسیر'),
            preserve_default=False,
        ),
    ]
