# Generated by Django 6.0.2 on 2026-04-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0007_tafsir_tafsir_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tafsir',
            name='tafsir_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tafsirs', to='quran.tafsirsource', verbose_name='منبع تفسیر'),
        ),
    ]
