# Generated by Django 6.0.2 on 2026-04-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0008_alter_tafsir_tafsir_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tafsirsource',
            options={'verbose_name': 'منبع تفسیر', 'verbose_name_plural': 'منابع تفسیر'},
        ),
        migrations.RenameField(
            model_name='surah',
            old_name='persian_name',
            new_name='name_fa',
        ),
        migrations.RenameField(
            model_name='surah',
            old_name='persian_second_name',
            new_name='second_name_fa',
        ),
        migrations.AlterField(
            model_name='ayah',
            name='text_fa',
            field=models.TextField(blank=True, verbose_name='متن کامل آیه (فارسی)'),
        ),
    ]
