# Generated by Django 6.0.2 on 2026-04-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0009_alter_tafsirsource_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surah',
            old_name='latin_name',
            new_name='name_en',
        ),
    ]
