# Generated by Django 6.0.2 on 2026-04-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0010_rename_latin_name_surah_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='tafsir',
            name='ayah_list',
            field=models.ManyToManyField(related_name='tafsir_list', to='quran.ayah', verbose_name='آیات مرتبط'),
        ),
    ]
