# Generated by Django 6.0.2 on 2026-04-30 12:34

from django.db import migrations


def migrate_tafsir_data(apps, schema_editor):
    Tafsir = apps.get_model('tafsir', 'Tafsir')

    for tafsir in Tafsir.objects.all():
        if tafsir.ayah:
            tafsir.ayah_list.add(tafsir.ayah)


def reverse_migrate(apps, schema_editor):
    Tafsir = apps.get_model('tafsir', 'Tafsir')

    for tafsir in Tafsir.objects.all():
        if tafsir.ayah_list.exists():
            tafsir.ayah = tafsir.ayah_list.first()
            tafsir.save()

class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0011_tafsir_ayah_list'),
    ]

    operations = [
    ]
