# Generated by Django 6.0.2 on 2026-04-30 12:53

from django.db import migrations


def migrate_tafsir_data(apps, schema_editor):
    Tafsir = apps.get_model('quran', 'Tafsir')

    for tafsir in Tafsir.objects.all():
        if tafsir.ayah:
            tafsir.ayah_list.add(tafsir.ayah)


def reverse_migrate(apps, schema_editor):
    Tafsir = apps.get_model('quran', 'Tafsir')

    for tafsir in Tafsir.objects.all():
        if tafsir.ayah_list.exists():
            tafsir.ayah = tafsir.ayah_list.first()
            tafsir.save()

class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0012_migrate_ayah_to_ayah_list'),
    ]

    operations = [
        migrations.RunPython(migrate_tafsir_data, reverse_migrate),

    ]
