# Generated by Django 6.0.2 on 2026-04-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0013_migrate_ayah_to_ayah_list2'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tafsir',
            name='quran_tafsi_ayah_id_1665c3_idx',
        ),
        migrations.AddIndex(
            model_name='tafsir',
            index=models.Index(fields=['order_priority'], name='quran_tafsi_order_p_f72e3f_idx'),
        ),
        migrations.RemoveField(
            model_name='tafsir',
            name='ayah',
        ),
    ]
