# Generated by Django 6.0.2 on 2026-05-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0014_remove_tafsir_quran_tafsi_ayah_id_1665c3_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tafsirsource',
            options={'ordering': ['order_priority'], 'verbose_name': 'منبع تفسیر', 'verbose_name_plural': 'منابع تفسیر'},
        ),
        migrations.AddField(
            model_name='tafsirsource',
            name='order_priority',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='اولویت ترتیب نمایش'),
        ),
    ]
