# Generated by Django 6.0.2 on 2026-05-04 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0015_alter_tafsirsource_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tafsir',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tafsirs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد کننده'),
            preserve_default=False,
        ),
    ]
