# Generated by Django 6.0.2 on 2026-05-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0016_tafsir_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tafsir',
            options={'verbose_name': 'تفسیر', 'verbose_name_plural': 'تفاسیر'},
        ),
        migrations.RemoveIndex(
            model_name='tafsir',
            name='quran_tafsi_order_p_f72e3f_idx',
        ),
        migrations.AlterField(
            model_name='ayah',
            name='text_prefix',
            field=models.CharField(blank=True, max_length=50, verbose_name='متن'),
        ),
        migrations.RemoveField(
            model_name='tafsir',
            name='order_priority',
        ),
    ]
