# Generated by Django 6.0.2 on 2026-06-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0017_alter_tafsir_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                   UPDATE quran_ayah
                    SET text_fa = REPLACE(
                                    REPLACE(
                                        REPLACE(text_fa, 'ٱ', 'ا'),
                                    'ا۟', 'ا'),
                                'و۟', 'و'
                                )
                   WHERE text_fa IS NOT NULL;
               """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
