# Generated by Django 6.0.2 on 2026-08-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0018_normalize_quran_text_fa'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE quran_tafsir
            SET text =
                regexp_replace(
                    regexp_replace(
                        regexp_replace(
                            text,
                            '(?<![.!؟])[\\r\\n]+',
                            ' ',
                            'g'
                        ),
                        '\\(\\s+',
                        '(',
                        'g'
                    ),
                    '\\s+\\)',
                    ')',
                    'g'
                )
            WHERE tafsir_source_id = 3;
        """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
