# Generated by Django 6.0.2 on 2026-08-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0019_normalize_nemuneh_tafsir_text'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE quran_tafsir
            SET text = regexp_replace(
                text,
                '^نکات[\\r\\n]+',
                '',
                'g'
            )
            WHERE tafsir_source_id = 1;
            """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
