# Generated by Django 6.0.2 on 2026-08-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0020_remove_extra_word_from_start_text'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                   UPDATE quran_tafsir
                   SET text = regexp_replace(
                       text,
                       '===',
                       E'\\n',
                       'g'
                   )
                   WHERE tafsir_source_id = 1
                     AND text LIKE '%===%';
               """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
