# Generated by Django 6.0.2 on 2026-10-04 21:07
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0021_remove_equal_sign_from_text'),
    ]

    operations = [
        TrigramExtension(),
    ]
