# Generated by Django 6.0.2 on 2026-10-04 21:13

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0022_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ayah',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_fa'], name='ayah_text_fa_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
